[package]
name = "xq"
version = "0.5.0"
authors = ["mi_sawa <mi.sawa.1216+git@gmail.com>"]
edition = "2021"
description = "A reimplementation of jq."
license = "MIT"
repository = "https://github.com/MiSawa/xq"
readme = "README.md"
exclude = [".github"]

[package.metadata.binstall]
pkg-url = "{ repo }/releases/download/v{ version }/{ name }-v{ version }-{ target }.tar.gz"
bin-dir = "{ name }-v{ version }-{ target }/{ bin }{ binary-ext }"
pkg-fmt = "tgz"
[package.metadata.binstall.overrides.x86_64-pc-windows-msvc]
pkg-url = "{ repo }/releases/download/v{ version }/{ name }-v{ version }-{ target }.{ archive-format }"
pkg-fmt = "zip"

[package.metadata.release]
pre-release-hook = ["cargo", "update", "--manifest-path", "./fuzz/Cargo.toml", "-p", "xq"]

[workspace]
members = [ "crates/*" ]

[[bin]]
name = "xq"
path = "src/bin/main.rs"
required-features = ["build-binary"]

[[bench]]
name = "prelude"
harness = false

[features]
default = ["build-binary"]
build-binary = [
  "anyhow",
  "clap",
  "clap-verbosity-flag",
  "simplelog",
  "serde_yaml",
  "toml",
  "bat"
]

[profile.release]
strip = "symbols"
lto = true
codegen-units = 1

[profile.dev.build-override]
opt-level = 3

[dependencies]
xq-lang = { path = "./crates/lang", version = "0.0.1" }

thiserror = "1.0.30"
log = "0.4.14"
imbl = "3.0.0"
sized-chunks = "0.7.0"
num = "0.4.0"
num-traits = "0.2.14"
num-derive = "0.4.2"
ordered-float = "4.2.0"
cast = "0.3.0"
itertools = "0.13.0"
derive_more = "0.99.17"
phf = { version = "0.11.2", features = ["macros"] }
serde = "1.0.136"
serde_json = "1.0.79"
html-escape = "0.2.9"
shell-escape = "0.1.5"
urlencoding = "2.1.0"
base64 = "0.22.1"
time = { version = "0.3.7", features = ["local-offset"] }
time-fmt = "0.3.4"
time-tz = { version = "2.0.0", features = ["system", "posix-tz"] }
onig = { version = "6.3.1", default-features = false }

# bin deps
clap = { version = "4.0.0", features = ["derive"], optional = true }
clap-verbosity-flag = { version = "2.0.0", optional = true }
serde_yaml = { version = "0.9.34", optional = true }
toml = { version = "0.8.13", optional = true }
anyhow = { version = "1.0.56", optional = true }
simplelog = { version = "0.12.0", optional = true }

[dependencies.bat]
version = "0.24.0"
default-features = false
features = ["build-assets", "regex-onig"]
optional = true

[dev-dependencies]
criterion = "0.5.1"
trycmd = "0.15.2"

